import numpy as np

# #按轴连接数组(numpy.concatenate)
# a = np.array([[1,2,3,4,5],[3,4,5,6,7]])
# print ('第一个数组：')
# print (a)
# print ('\n')
# b = np.array([[5,6,7,8,9],[7,8,9,10,11]])
# print ('第二个数组：')
# print (b)
# print ('\n')
#  # 两个数组的维度相同
# print ('沿轴 0 连接两个数组：')
# print (np.concatenate((a,b)))
# print ('\n')
# print ('沿轴 1 连接两个数组：')
# print (np.concatenate((a,b),axis = 1))

# #使用堆栈函数连接数组(numpy.stack)
# a = np.array([[1,2,3,4,5],[3,4,5,6,7]])
# print ('第一个数组：')
# print (a)
# print ('\n')
# b = np.array([[5,6,7,8,9],[7,8,9,10,11]])
# print ('第二个数组：')
# print (b)
# print ('\n')
# print ('沿轴 0 堆叠两个数组：')
# print(np.stack((a,b),0))
# print("\n")
# print("沿轴1堆叠两个数组：")
# print(np.stack((a,b),1))

# #沿行堆叠数组(numpy.hstack)
# a = np.array([[1,2,3,4,5],[3,4,5,6,7]])
# print ('第一个数组：')
# print (a)
# print ('\n')
# b = np.array([[5,6,7,8,9],[7,8,9,10,11]])
# print ('第二个数组：')
# print (b)
# print ('\n')
# print ('水平堆叠：')
# c = np.hstack((a,b))
# print (c)
# print ('\n')

# #沿列堆叠数组(numpy.vstack)
# a = np.array([[1,2,3,4,5],[3,4,5,6,7]])
# print ('第一个数组：')
# print (a)
# print ('\n')
# b = np.array([[5,6,7,8,9],[7,8,9,10,11]])
# print ('第二个数组：')
# print (b)
# print ('\n')
# print ('竖直堆叠：')
# c = np.vstack((a,b))
# print (c)

# #沿高度堆叠(numpy.dstack)
# a = np.array([[1,2,3,4,5],[3,4,5,6,7]])
# b = np.array([[5,6,7,8,9],[7,8,9,10,11]])
# arr = np.dstack((a, b))
# print(arr)